services:
  plex:
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    container_name: plex
    network_mode: host
    environment:
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      PLEX_GID: 1000
      PLEX_UID: 1000
    volumes:
      - /home/miguely/docker/plex/config:/config
      - /home/miguely/docker/plex/transcodes:/transcode
      - /media/multimedia/Movies:/movies
      - "/media/multimedia/TV Shows:/tv"
      - /dev/dri:/dev/dri
