defaults:
  create:
    create_parent_dirs: true
  exec:
    echo: true
  link:
    force: true
    relink: true
  brew:
    adopt_casks: true

steps:
  - link:
      - ~/Library/LaunchAgents/sh.brew.update.plist: sh.brew.update.plist
      - ~/Library/LaunchAgents/sh.brew.upgrade.plist: sh.brew.upgrade.plist
  - create:
      - ~/Library/Workflows/Services
  - exec:
      - cmd: ./defaults/base.sh
        skip_in_ci: true
        description: Running the base macOS sensible defaults, shared across all configs
      - cmd: launchctl load /Users/$USER/Library/LaunchAgents/sh.brew.update.plist
        description: Setting brew update to run on a regular basis.
      - cmd: launchctl load /Users/$USER/Library/LaunchAgents/sh.brew.upgrade.plist
        description: Setting brew upgrade to run on a regular basis.
      - cmd: ./install_workflows.sh
        skip_in_ci: true
        description: Installing useful Automator Workflows as Services.
  - brew:
      formula:
        - nvim
        - vim
        # Version control
        - git
        - gh
        - hub
        - lazygit
        - jj
        # Other stuff
        - comby
        - openssl
        # Shell stuff
        - fd
        - fzf
        - shellcheck
        - shfmt
        - ripgrep
        - tmux
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting
        # Programming languages & Tools
        - angular-cli
        - buildifier
        - cargo-binstall
        - go
        - gopls
        - openssl
        - pre-commit
        - python3
        - pyenv
        - pipx
        - rbenv
        - ruby
        - rustup
        - typescript
        # Linters
        - markdownlint-cli
        - pylint
        - yapf
        # Other
        - baobab # kinda like disk-inventory-x
        - hugo
        # Necessary for Hugo stuff
        - sass/sass/sass
        # typst
        - typst
        - typstfmt
        - typstyle

  - brew:
      formula:
        # This is bazelisk on mac, bazel on linux
        - bazelisk
        # Dependency management
        - mas
        # macOS gui helpers
        # dockutil is not working currently on brew
        - dockutil
        - switchaudio-osx
        # Other stuff
        - dezoomify-rs
        - exiftool
        - kubernetes-cli
        - graphviz
        - typst
        - typstyle
      cask:
        # Programming stuff
        - github
        - visual-studio-code
        - textmate
        - sourcetree
        # Basics
        - jordanbaird-ice
        - google-chrome
        - firefox
        - font-meslo-lg-nerd-font
        - iterm2
        - obsidian
        # Communication
        - discord
        - signal
        # Media
        - netnewswire
        - steam
        - vlc
        # Helpful tools
        - disk-inventory-x
        - omnidisksweeper # kinda like disk-inventory-x
        - mysides
        - raycast
        # Typesetting
        - font-roboto
        - font-source-sans-3
        - font-fontawesome
  - brew:
      # This is a separate brew directive so it can be skipped in CI.
      # Some of these formulae and casks either take too long to install or just
      # don't install in CI.
      # `mas` actions should never be run in CI since they depend on a
      # Mac App Store login.
      skip_in_ci: true
      mas:
        # Notetaking & Organization
        GoodNotes: 1444383602
        Things: 904280696
        # Utilities
        Dashlane: 517914548
        Magnet: 441258766
        Theine: 955848755
        Tooth Fairy: 1191449274
        BetterSnapTool: 417375580
        # Safari Extensions
        Hush: 1544743900
        # Creative
        Darkroom: 953286746
        Kindle: 302584613
        # Office
        OneDrive: 823766827
        Outlook: 985367838
