version: 2.1

executors:
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:202107-02
  macos: # macos executor running Xcode
    macos:
      xcode: 15.0.0


jobs:
  test:
    parameters:
      os:
        type: executor
      config_name:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: Install and set Linuxbrew
          command: .circleci/install_homebrew.sh
      - run:
          name: Install dotfiles
          command: |
            brew tap miguelandres/homebrew-tap
            brew install dotfiles-rs
      - run:
          name: Apply config << parameters.os >>
          command: |
            dotfiles --log-level-filter debug apply-config << parameters.config_name >>.yaml
            echo "=========================================="
            echo "Running dotfiles again to test idempotence"
            echo "=========================================="
            dotfiles --log-level-filter debug apply-config << parameters.config_name >>.yaml

workflows:
  linux-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              config_name: [linux]
  mac-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [macos]
              config_name: 
                - mac-personal-migue
                - mac-personal-mati
                - mac-work
