services:
  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
      - ~/.local/share/docker/volumes:/var/lib/docker/volumes
