version: '3.7'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: always
    environment:
      - PORT=80
    ports:
      - 80:80
    volumes:
      - /home/miguely/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
