defaults:
  create:
    create_parent_dirs: true
  link:
    create_parent_dirs: true
    force: true

steps:
  - create:
      - ~/.oh-my-zsh/custom/plugins
      - ~/.oh-my-zsh/custom/themes
  - exec:
      - cmd: "[ -d ~/.oh-my-zsh/custom/plugins/alias-tips ] || git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips"
        description: Cloning alias-tips for oh-my-zsh
      - cmd: "[ -d ~/.oh-my-zsh/custom/themes/powerlevel10k ] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k"
        description: Cloning the powerlevel10k theme for oh-my-zsh
  - link:
      - ~/.oh-my-zsh/custom/plugins/_bazel: custom/plugins/_bazel
      - ~/.zshrc: zshrc
      - ~/.zshenv: zshenv
      - ~/.zshrc-imports/.aliases: zshrc-imports/aliases
      - ~/.p10k.zsh: p10k.zsh
