defaults:
  create:
    create_parent_dirs: true
  link:
    create_parent_dirs: true
    force: true

steps:
  - brew:
      formula:
        # Shell tools
        - fzf
        - rbenv
        - romkatv/powerlevel10k/powerlevel10k
        - shellcheck
        - shfmt
        - zsh
        - zsh-autosuggestions
        - zsh-completions
        - zsh-syntax-highlighting
  - create:
      - ~/.oh-my-zsh/custom/plugins
      - ~/.oh-my-zsh/custom/themes
  - exec:
      - "[ -d ~/.oh-my-zsh/custom/plugins/alias-tips ] || git clone https://github.com/djui/alias-tips.git ~/.oh-my-zsh/custom/plugins/alias-tips"
  - link:
      - ~/.oh-my-zsh/custom/plugins/_bazel: custom/plugins/_bazel
      - ~/.zshrc: zshrc
      - ~/.zshenv: zshenv
      - ~/.zshrc-imports/.aliases: zshrc-imports/aliases
      - ~/.p10k.zsh: p10k.zsh
