defaults:
  create:
    create_parent_dirs: true
  exec:
    echo: true
  link:
    force: true
    relink: true

steps:
  - exec:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - bash <(curl -sL get-comby.netlify.app)
  - apt:
      package:
        # Command line basics
        - fzf
        - git
        - gh
        - hub
        - tmux
        - vim
        - zsh
        # Programming
        - default-jdk
        - kotlin
        - pre-commit
        - python3
        - ruby
        - scala
        - uidmap
