defaults:
  create:
    create_parent_dirs: true
  exec:
    echo: true
    skip_in_ci: true
  link:
    force: true
    relink: true

steps:
  - exec:
      - cmd: sudo apt update
        description: Update apt
  - apt:
      skip_in_ci: true
      package:
        # Command line basics
        - fzf
        - git
        - gh
        - hub
        - tmux
        - vim
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
