defaults:
  create:
    create_parent_dirs: true
  exec:
    echo: true
    skip_in_ci: true
  link:
    force: true
    relink: true

steps:
  - exec:
      - cmd: sudo apt update
        description: Update apt
      - cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
        description: Install rustup
      - cmd: . "$HOME/.cargo/env"  && rustup toolchain install nightly
        description: install rust nightly
      - cmd: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        description: Install cargo-binstall
  - apt:
      skip_in_ci: true
      package:
        # Command line basics
        - fzf
        - git
        - gh
        - hub
        - tmux
        - vim
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  - exec:
      - cmd: cargo binstall -y --strategies crate-meta-data jj-cli
        description: Install jj-cli
      - cmd: curl https://pyenv.run | bash
        description: Install pyenv
