defaults:
  create:
    create_parent_dirs: true
  exec:
    echo: true
  brew:
    force_casks: true
  link:
    force: true
    relink: true

steps:
  - apt:
      package:
        # Command line basics
        - docker
        - fzf
        - git
        - tmux
        - vim
        - zsh
        # Programming
        - default-jdk
        - python3
        - scala
  - exec:
      - pip3 install pre-commit
