defaults:
  create:
    create_parent_dirs: true
  exec:
    echo: true
  link:
    force: true
    relink: true

steps:
  - apt:
      package:
        # Command line basics
        - fzf
        - git
        - tmux
        - vim
        - zsh
        # Programming
        - default-jdk
        - kotlin
        - pre-commit
        - python3
        - ruby
        - scala
        - uidmap
