name: Apply personal configuration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  apply-configs:
    name: ${{ matrix.make.name }} (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.gh_env }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly]
        target:
          - name: linux
            gh_env: ubuntu-latest
          - name: mac-personal-migue
            gh_env: macos-latest
          - name: mac-personal-mati
            gh_env: macos-latest
          - name: mac-work
            gh_env: macos-13

    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install dotfiles
        run: |
          brew tap miguelandres/homebrew-tap
          brew install dotfiles-rs
      - if: matrix.target.gh_env == 'macos-latest'
        name: Preinstall python
        run: |
          brew install python || echo "error installing python,"
          brew link --overwrite python
      - name: Apply config ${{ matrix.target.name }}
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          dotfiles --log-level-filter debug apply-config ${{ matrix.target.name }}.yaml
          echo "=========================================="
          echo "Running dotfiles again to test idempotence"
          echo "=========================================="
          dotfiles --log-level-filter debug apply-config ${{ matrix.target.name }}.yaml
