name: Apply personal configuration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  apply-configs:
    name: ${{ matrix.make.name }} (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.gh_env }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly]
        target:
          - name: mac-personal-migue
            gh_env: macos-11
          - name: mac-personal-mati
            gh_env: macos-11
          - name: mac-work
            gh_env: macos-11

    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          brew tap miguelandres/homebrew-tap
          brew install dotfiles-rs
      - name: Apply config {{matrix.target.name}}
        run: |
          dotfiles --log-level-filter debug apply-config -n {{matrix.target.name}}.yaml
